### ISSUE TITLE
When testrail server is https and use custom SSL certificate, the plugin can't connect the testrail server

### ISSUE THREAD

**Issue by Zrollan** [Legionivo/Allure-to-TestRail-exporter#1]
I try to use this plugin in IntelliJ, but can't connect the testrail server(https)

![image](https://user-images.githubusercontent.com/24754767/72317113-32699100-36d3-11ea-8d33-2a786fa22b0c.png)

![image](https://user-images.githubusercontent.com/24754767/72317228-82485800-36d3-11ea-92cb-98fd292aa26a.png)

**Comment by Zrollan** [comment]
Can the plugin trust all SSL certificates or trust unsafe SSL certificates?

**Comment by Legionivo** [comment]
Hello @Zrollan. Thanks for letting me know about the issue. Could you please manually install attached plugin and verify that it works? 
[Allure to TestRail exporter plugin-1.5.1.zip](https://github.com/Legionivo/Allure-to-TestRail-exporter/files/4180732/Allure.to.TestRail.exporter.plugin-1.5.1.zip)

**Comment by Legionivo** [comment]
Fixed in v 1.5.2
