### ISSUE TITLE
Allure Annotation values are not exported to TestRail

### ISSUE THREAD

**Issue by arturmkr** [Legionivo/Allure-to-TestRail-exporter#3]
Having following code in the test:

```
  @Step("response should have {0}")
  public void shouldHaveThisVal(String value) {
  		//some code 
  }
```

```
  @Epic(value = "11")
  @Feature(value = "22")
  @Story(value = "333")
  @DisplayName(value = "something")
  @Test
  void someThingTest() {
    shouldHaveThisVal("aaa");
  }
```

As a result into TestRail following step is exported:
`response should have {0}`

Expected result:
`response should have aaa `

**Comment by Legionivo** [comment]
@arturmkr you should use the name of parameter: `@Step("response should have {value}")`

**Comment by arturmkr** [comment]
@Legionivo 
Please check package `"par"`:
https://github.com/arturmkr/testrailToAllure/tree/main/src/test/java/com/example/TestRail/par

Having `{0}` in the Allure annotation would be displayed as `{0}` in the TestRail:
https://github.com/arturmkr/testrailToAllure/blob/1580e65622f0b47ea027488c32dd7fbda6466e83/src/test/java/com/example/TestRail/par/Meth.java#L10

Having `{carCheck}` on that line doesn't work.

**Comment by Legionivo** [comment]
@arturmkr please read official documentation and use correct approach - https://docs.qameta.io/allure/#_steps_3 
![Screenshot 2021-07-19 at 11 13 07](https://user-images.githubusercontent.com/12167296/126135323-d0146db5-3449-4b38-a0af-99d9099d3a5a.png)

**Comment by arturmkr** [comment]
@Legionivo but if to change  `{0}` to `{carCheck}` on this line:
https://github.com/arturmkr/testrailToAllure/blob/1580e65622f0b47ea027488c32dd7fbda6466e83/src/test/java/com/example/TestRail/par/Meth.java#L10

Export won't work at all.

**Comment by Legionivo** [comment]
Initially you asked about `shouldHaveThisVal("aaa");`, now you're pointing to absolutely different code with interface. In case of interface it will not work because there is no value in method parameter, like "aaa" in your first comment.

**Comment by arturmkr** [comment]
It even won't work if changing interface to abstract class.
